# Generated by Django 3.1.8 on 2021-06-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posthog", "0156_insight_short_id"),
    ]

    operations = [
        migrations.AddField(model_name="plugin", name="metric_names", field=models.JSONField(default=list, null=True),),
    ]
