# Generated by Django 3.1.8 on 2021-06-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posthog", "0157_plugin_metric_names"),
    ]

    operations = [
        migrations.RemoveField(model_name="plugin", name="metric_names",),
        migrations.AddField(model_name="plugin", name="metrics", field=models.JSONField(default=dict, null=True),),
    ]
